[versions]
kotlin = "2.2.0"
kotlinter = "5.0.2"
kermit = "2.0.5"
central = "1.2.8"
dokka = "2.0.0"
compose = "1.8.10-alpha01"

[libraries]
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[plugins]
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
central = { id = "cn.lalaki.central", version.ref = "central"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
